#!/bin/bash
echo "🚀 Starting Multi-Account Ledger Desktop App..."
echo ""
echo "Build complete! Your desktop app is ready."
echo ""
echo "📁 App Location: dist/packages/linux-unpacked/"
echo ""
echo "To run your desktop app:"
echo "1. Navigate to: cd dist/packages/linux-unpacked/"
echo "2. Run: ./fusion-starter"
echo ""
echo "🎯 Features included:"
echo "• Complete Multi-Account Ledger functionality"
echo "• PDF & Excel export capabilities"
echo "• Local data storage"
echo "• Native desktop menus and shortcuts"
echo ""
echo "Starting the app now..."
cd dist/packages/linux-unpacked && ./fusion-starter
